### ISSUE TITLE
Livrable ?

### ISSUE THREAD

**Issue by rgrunbla** [Witaek/RusTracker#10]
Hello, sur Moodle je vois ça:

![image](https://user-images.githubusercontent.com/42433779/161009035-9ea9e9a1-b780-48aa-9cb3-2b88b39661db.png)

Je viens de ré-ouvrir la soumission pour vous, jusqu'à 23h55, avez vous quelque chose à uploader niveau livrable ? (screenshots, etc)

**Comment by rgrunbla** [comment]
@blaaass @GuilhemHnr @Witaek @ArthurChauve

**Comment by Witaek** [comment]
Re-bonjour, 

Les attentes concernant le livrable 2 ne sont pas nécessairement téléversable sur moodle. Pendant l'un de nos points rencontres pendant les vacances (03/03/2022) vous aviez indiqué vos attentes pour le livrable 2 (prototype) :   

* Backend : test des fonctions (calcul de vitesse, position, etc) sur plusieurs messages binaires exemples, réception des messages, démodulation (traitement I&Qs)
* Frontend : Afficher une carte avec des points mouvants, possibilité d'afficher les infos sur les points (vitesse, position, etc)

Côté backend, nous avons beaucoup plus avancé que prévu puisque nous réceptionnons, démodulons, et interprétons les messages directement reçu par les antennes, comme vous l'avez constaté lors de notre rencontre du 16/03/22.
Côté frontend, on a pas encore tout à fait réussi à mettre en place l'interface graphique mais c'est sur la bonne route (nous venons d'en discuter).

Voici une citation du "guide du livrable 2" sur moodle : "L’encadrant fixe le format du livrable 2. Cela peut par exemple être un simple «tag» sur le dépôt git, ou une archive «tgz» déposée sur moodle".

Étant donné la nature du livrable 2 que vous nous avez demandé, nous avons considéré que l'avancée du projet sur notre git faisait foi de livrable 2. 

Nous pouvons toutefois faire un tag si vous le désirez.
Merci ! 

@rgrunbla

**Comment by Witaek** [comment]
Voulez-vous qu'on upload des screens de la réceptions des messages dans le terminal ? (Ce qu'on vous a présenté le 16/03)

**Comment by GuilhemHnr** [comment]
Re-Bonjour monsieur,

Voilà deux petits screens.
L'interface graphique reste peu avancée, et c'est principalement une reprise de l’exemple de yew-leaflet-rs, adapté au projet, cependant ça devrait pas mal évolué, car cela nous sert juste de bonne base de départ pour travailler.
Par ailleurs, on déplace l'interface graphique dans un autre repository git pour travailler dessus plus facilement : 
https://github.com/GuilhemHnr/trackui

Enfin, le problème du logo s'est réglé en ajoutant une ligne <link data-trunk rel="copy-dir" href="ressources"> dans le index.html qu'utilise trunk pour le WebAssembly sous rust. Cela me permet d'avoir accès au directory dans le quel se trouve mon png dans le localhost.

![plane01](https://user-images.githubusercontent.com/98390029/161037961-816cb6c4-e89b-4bb7-b98d-2aa61bca69db.png)
![trackui](https://user-images.githubusercontent.com/98390029/161038010-f0da4ed1-b3d7-4ed1-b178-c1e3ba0213db.png)
