### ISSUE TITLE
Prochain point?

### ISSUE THREAD

**Issue by rgrunbla** [Witaek/RusTracker#13]
Hello,

À quand est fixé notre prochain point d'échange ? @blaaass @ArthurChauve @Witaek @GuilhemHnr

**Comment by Witaek** [comment]
Bonjour, 

Est-ce que le jeudi 14 avril à 19h ou 20h vous conviendrait ? (on vous laisse le choix de l'heure)

Merci ! 
@rgrunbla

**Comment by rgrunbla** [comment]
jeudi 14 avril à 19h, parfait pour moi, c'est noté.
