### ISSUE TITLE
Lien point rencontre 14/04 à 19h

### ISSUE THREAD

**Issue by Witaek** [Witaek/RusTracker#14]
Bonjour, 

Voici le lien pour le point rencontre de ce soir : https://meet.google.com/xox-gujv-pec

@GuilhemHnr @rgrunbla @blaaass @ArthurChauve

**Comment by rgrunbla** [comment]
Parfait. Je suis dispo maintenant si vous êtes tous aussi dispo, à vous de me dire.

**Comment by Witaek** [comment]
Parfait pour nous, nous sommes en ligne ! @rgrunbla
