### ISSUE TITLE
Prochain point 

### ISSUE THREAD

**Issue by Witaek** [Witaek/RusTracker#15]
Dans la continuité de la réunion de ce soir, serait-il possible de se revoir la semaine du 25 ?

@rgrunbla

**Comment by rgrunbla** [comment]
Je vous laisse le choix, donnez moi une date / heure dans la semaine du 25.

**Comment by Witaek** [comment]
Est-ce que le présentiel est possible cette semaine ?
Merci
@rgrunbla

**Comment by rgrunbla** [comment]
Comme d'habitude, si c'est dans des horaires compatibles avec mon temps de trajet vers TSP, ça va (i.e. 9h30 < t < 17h30 pour faire large).

**Comment by rgrunbla** [comment]
@Witaek up ?

**Comment by rgrunbla** [comment]
Hello,
On peut dire le jeudi 28 à 13h30, dans ce cas.

**Comment by Witaek** [comment]
C'est noté ! @rgrunbla
