### ISSUE TITLE
[Session Code]

### ISSUE THREAD

**Issue by ArthurChauve** [Witaek/RusTracker#17]
Bonjour monsieur, 

Nous aurions besoin de votre aide pour implémenter le tableau. Serait il possible de réaliser une session code, comme vous nous l'aviez proposé, en jeudi à 15h00 distanciel  ou vendredi dans la matinée ? 

Merci beaucoup !
@rgrunbla

**Comment by rgrunbla** [comment]
Demain 15h c'est bien ça ? Si c'est ça aucun problème.

On 11 May 2022 19:34:03 CEST, ArthurChauve ***@***.***> wrote:
>Bonjour monsieur, >
>
>
>Nous aurions besoin de votre aide pour implémenter le tableau. Serait il possible de réaliser une session code, comme vous nous l'aviez proposé, en jeudi à 15h00 distanciel  ou vendredi dans la matinée ? >
>
>
>Merci beaucoup !
>
***@***.*** >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/Witaek/RusTracker/issues/17
>
>You are receiving this because you were mentioned.
>
>
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by GuilhemHnr** [comment]
Parfait, on vous envoie un lien de connexion peu avant

**Comment by GuilhemHnr** [comment]
Voici le lien google meet pour la réunion de 15h

Session Code
Jeudi, 12 mai · 3:00 à 4:00pm
Informations de connexion Google Meet
Lien de l'appel vidéo : https://meet.google.com/ukc-npst-quw
