### ISSUE TITLE
Soutenance

### ISSUE THREAD

**Issue by rgrunbla** [Witaek/RusTracker#19]
Bonjour,

Votre soutenance aura lieu mardi 31 mai à 9h, avez vous une incompabilité avec cette date ?

Rémy

**Comment by rgrunbla** [comment]
@ArthurChauve @Witaek @GuilhemHnr @blaaass

**Comment by blaaass** [comment]
Bonjour,

Hélas nous avons des cours prévu à cette heure là, mais notre emploi du temps a des créneaux spécialement prévu le mardi 31 mai à partir de 14h et toute la journée du mercredi 1er juin.

Bastian

**Comment by rgrunbla** [comment]
Bonjour,

Est-ce que 12h30 le mardi conviendrait ?

**Comment by rgrunbla** [comment]
ps: envoyez moi vos numéros par email comme ça je peux vous contacter en synchrone.

**Comment by rgrunbla** [comment]
@blaaass @ArthurChauve @GuilhemHnr @Witaek up

**Comment by Witaek** [comment]
![Screenshot_2022-05-18-09-10-00-60_3481fdfaf807158df2e382fd7e3ae703.jpg](https://user-images.githubusercontent.com/93662897/168983813-89644f16-462d-4908-bc71-81f224f02561.jpg)

@rgrunbla

**Comment by Witaek** [comment]
Bonjour @rgrunbla. Malheureusement à 12h30 il y a un rattrapage d'exam dont nous n'avons pas encore les résultats donc on ne peut pas garantir que tout le monde soit disponible à ce moment.

**Comment by rgrunbla** [comment]
Jeudi, 11h30, ça fonctionnerait ?

**Comment by rgrunbla** [comment]
@Witaek

**Comment by GuilhemHnr** [comment]
Bonjour Monsieur,

Je crains que nous souhaitons éviter un tel horaire qui s'intercale entre deux CF.
Toutefois nous disposons de créneaux large réservé à la soutenance (le 31/05 de 14h à 18h ou l'ensemble du 01/06), y a-t-il un conflit les concernant ?

@rgrunbla

**Comment by rgrunbla** [comment]
Bonjour,

Le planning envoyé il y a 2 heures ne montre rien le mardi matin, ce qui était mon plan initial, est-ce que ça pose vraiment problème ? Comme précisé dans mon [message d'hier](https://github.com/Witaek/RusTracker/issues/19#issuecomment-1128468077), j'aimerais donc avoir vos numéros de téléphones pour échanger de manière synchrone, sinon on va pas s'en sortir.

**Comment by Witaek** [comment]
C'est parceque nous n'avons pas tous les mêmes emplois du temps. Mais on s'est arrangé, ça devrait être bon pour le **mardi 31 à 9h**.

Voici nos numéros : 

Romain Amédée : 0761371008
Guilhem honoré : 06 52 09 80 06
Bastian larvor : 06 47 01 83 56
Arthur chauve : 07 82 38 43 44

@rgrunbla

**Comment by rgrunbla** [comment]
Merci beaucoup pour la réactivité. J'apellerai Romain vers ~12h45/50 pour tout bien vérifier qu'on est d'accords.

**Comment by Witaek** [comment]
Pas de soucis @rgrunbla
