### ISSUE TITLE
Entraînement soutenance 

### ISSUE THREAD

**Issue by Witaek** [Witaek/RusTracker#21]
Bonjour, 

Est-ce que dimanche soir vous conviendrait pour placer l'entrainement à la soutenance ? L'heure de votre choix.

Merci ! 
@rgrunbla

**Comment by rgrunbla** [comment]
Hello,

On peut dire 17h30 dimanche soir ?

Concernant votre « vraie  » soutenance, elle aura finalement lieu le mardi après-midi à 13h30 ou 14h30. Je reviens vers vous pour le détail.

@Witaek @ArthurChauve @GuilhemHnr @blaaass 

Rémy

**Comment by Witaek** [comment]
Malheureusement je serais dans le train à cette heure là. Une heure à partir de 18h45 vous conviendrait-elle ? Désolé nous sommes conscients que cela est tard. Sinon nous allons nous débrouiller pour trouver un autre moment.

Romain
@rgrunbla

**Comment by rgrunbla** [comment]
Va pour 18h45.

**Comment by rgrunbla** [comment]
Votre soutenance aura lieu à 13h30 (on avait pas décidé, maintenant, oui).

**Comment by GuilhemHnr** [comment]
Bonsoir Monsieur,
J'ai un cf qui se termine juste à 13h15. Je peux me présenter à 13h30 sans soucis, j'apprécierai juste si pouvais avoir une marge supplémentaire.
Toutefois, ce n'est pas particulièrement gênant si jamais vous avez d'autres contraintes.
Désolé d'avoir prévenu tardivement.

@rgrunbla

**Comment by rgrunbla** [comment]
@14h, dans ce cas. Ça sera en F216.

**Comment by GuilhemHnr** [comment]
Merci Monsieur,
Bonne soirée
