### ISSUE TITLE
Mini idée pour la présentation

### ISSUE THREAD

**Issue by rgrunbla** [Witaek/RusTracker#22]
Hello,

Si vous prenez les positions GPS de l'ensemble des avions pendant 24h (par exemple, en faisant une simple boucle en bash qui fait un `curl http://157.159.195.63/planes.geojson` et extrait les données avec [jq](https://stedolan.github.io/jq/)), vous pourrez faire, théoriquement, une sorte de carte de couverture de l'antenne en affichant tout ces points, un peu à la https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Example_radio_coverage_map.png/1280px-Example_radio_coverage_map.png?1653423196248 mais avec une seule couleur.

Ça pourrait être sympa pour votre présentation !

**Comment by GuilhemHnr** [comment]
Bonjour Monsieur, 
C'est en effet une bonne idée, on va étudier sa mise en pratique !
