### ISSUE TITLE
introspection

### ISSUE THREAD

**Issue by GuilhemHnr** [Witaek/RusTracker#25]
Bonsoir Monsieur,

D'abord, on vous remercie à nouveau pour les derniers messages.
En l'absence de réponse, on se demandait si vous aviez bien vu notre mail pour l'introspection que vous nous proposiez.

Cordialement.

@rgrunbla

**Comment by rgrunbla** [comment]
Bien reçu. J'ai mis des notes sur l'interface de moodle, arrivez vous à les voir ? C'est entre 16 et 18: (1*16, 1*17, 2*18).

**Comment by GuilhemHnr** [comment]
Personnellement, je ne vois pas la note, mais je ne vérifie peut être pas au bon endroit. Il est toutefois probable que l'on n'y ait accès que quand l'ensemble des élèves auront reçus leurs notes.
Dans tous les cas, merci beaucoup pour votre réponse
