### ISSUE TITLE
Problème ZeroMQ

### ISSUE THREAD

**Issue by Witaek** [Witaek/RusTracker#9]
Bonjour Monsieur, 

Nous sommes en train d'essayer de faire fonctionner ZeroMQ avec une architecture PUSH/PULL.

Nous rencontrons quelques difficultées pour le faire fonctionner ( rien côté réception, on est même pas sûr d'émettre des messages).

Serait-il possible de vous rencontrer afin de régler ce soucis ? 

Merci d'avance.

@rgrunbla

**Comment by rgrunbla** [comment]
Bonjour @Witaek @ArthurChauve @GuilhemHnr @blaaass, je suis disponible toute la journée d'aujourd'hui !

**Comment by Witaek** [comment]
Cela vous convient-il si nous passons après 18h ?
@rgrunbla

**Comment by rgrunbla** [comment]
Hello, pas vraiment (j'ai une heure de trajet pour rentrer chez moi)… Je suis dispo en visio toute la journée, aussi, si besoin.

**Comment by rgrunbla** [comment]
Hello, du nouveau de ce côté ? @Witaek @ArthurChauve @GuilhemHnr

**Comment by Witaek** [comment]
Pas vraiment. Serait-il possible de vous voir jeudi matin ? (Désolé nos emplois du temps pour cette semaine sont assez contraignants(

**Comment by rgrunbla** [comment]
Je suis en remote toute la semaine à part lundi ( conférence ) donc faisons ça en visio. Pouvez vous trouver un créneau de 30 / 45 minutes, n'importe quand?

On 27 March 2022 21:20:11 CEST, "Witaek [Romain]" ***@***.***> wrote:
>Pas vraiment. Serait-il possible de vous voir jeudi matin ? (Désolé nos emplois du temps pour cette semaine sont assez contraignants(
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/Witaek/RusTracker/issues/9#issuecomment-1080002238
>
>You are receiving this because you were mentioned.
>
>
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Witaek** [comment]
Dans tous les cas le plus simple pour nous reste jeudi matin. Une certaine heure vous arrange-t-elle ?

@rgrunbla

**Comment by rgrunbla** [comment]
8h, sachant que je commence autre chose à 8h30, ça vous va. Je vous upload un exemple de zmq en rust ce soir.

On 27 March 2022 21:44:37 CEST, "Witaek [Romain]" ***@***.***> wrote:
>Dans tous les cas le plus simple pour nous reste jeudi matin. Une certaine heure vous arrange-t-elle ?
>
***@***.*** 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Witaek/RusTracker/issues/9#issuecomment-1080005948
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by rgrunbla** [comment]
@Witaek @ArthurChauve @GuilhemHnr https://github.com/rgrunbla/RustZmqExample voilà un exemple de code ultra simple qui montre comment recevoir / envoyer des trucs en zmq sur la même machine.

1. Lancer cargo run server dans un terminal
2. Lancer cargo run client dans un autre terminal (le serveur doit bien être démarré en premier)

À travers internet, c'est le même principe, sauf qu'au lieu de mettre `tcp://127.0.0.1:1234`, vous mettez une ip publique avec un port adapté (attention aux pare-feux, attention au NAT). 

Il est possible d'utiliser udp (`udp://127.0.0.1:1234`) ou, si c'est pour des communications intra machine, de la mémoire partagée avec par exemple `inproc:///tmp/foobar` qui créera un fichier foobar dans /tmp comme point commun entre le serveur et le client.

Dites moi si ça fonctionne comme vous voulez / si vous avez besoin de plus d'info.

**Comment by Witaek** [comment]
Merci ! ça fonctionne bien ! 
On a peut-être quelques questions à vous poser niveau interface graphique donc on est partant pour maintenir le rdv jeudi matin à 8h.

**Comment by rgrunbla** [comment]
Parfait, mettez le lien de visio ici, que je puisse m'y connecter à 8h pétantes (ou alors carrément 7h45), et on pourra pas trop dépasser. En attendant, si vous avez des questions auxquelles je peux répondre en asynchrone, n'hésitez pas à les mettre ici / à créer une nouvelle issue comme ça je peux commencer à y réflechir.

**Comment by Witaek** [comment]
@rgrunbla normalement vous pourrez vous connecter à ce lien : https://meet.google.com/fhc-zeot-zvg
